
[Config]
	"Bismuth Ore Generation" = true
	"Malachite Ore Generation" = true
	"Nullstone Layers Generation" = true
	"Nullstone Patches Generation" = false
	#Defines if Ooze will occasionally break some blocks below it
	"Ooze Absorbing" = true
	#Defines if radiation is emmited from radiating blocks
	"Radiation Emissions" = true
	#Defines whether enduring vines will grow Adamantite Nodes
	"Adamantite Renewability" = true
	#Defines whether Portal Flasks can capture or place End Portals
	"Portal Flask Capturing" = true
	#Decreasing this value from 0 - 1 will make the generated biomes rarer
	"Biome Frequency" = 1.0
	#The amount of blocks enderneath tunnels will dig upwards before stopping
	"Enderneath Tunnel Limit" = 70.0
	#Defines whether chorloam blocks will teleport the player to nearby chloram blocks
	"Chorloam Teleporting" = true

